spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal/gis_data
    username: politbook_user_pgsql
    password: pgSQLPasswordUser_politbook
    driver-class-name: org.postgresql.Driver

mongo:
  host: host.docker.internal
  port: 27017
  database: gis
  username: root
  password: example
  authentication-database: admin