spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        jdbc:
          batch_size: 100
          
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/