spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mongo:
  host: 127.0.0.1
  port: 27017
  database: mongo_test
  username: root
  password: example
  authentication-database: admin