spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mongo:
  host: host.docker.internal
  port: 27017
  database: mongo_test
  username: root
  password: example
  authentication-database: admin